<?php
    
namespace App\Controller;

use App\Controller\AppController;
use Cake\Event\Event;
use Cake\Auth\DefaultPasswordHasher;
/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

class UsuariosController extends AppController{

    public function initialize(){
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->loadComponent('Upload');
    }

    public function add(){
        $usuario = $this->Usuarios->newEntity();
        if ($this->request->is('post')){
            $this->request->data['regra'] = 'Aluno';
            $this->request->data['senha'] = $this->_setPassword($this->request->data['senha']);
            $usuario = $this->Usuarios->patchEntity($usuario, $this->request->data);
            if($this->Usuarios->save($usuario)){
                $this->Flash->success(__('Usuário adicionado com sucesso.'));
                $this->Auth->setUser($this->request->data);
                return $this->redirect('/');
            }
            $this->Flash->error(__('Não é possível adicionar o usuário.'));
        }
        $this->set('title', 'Adicionar Usuário');
    }
	
	public function login(){
        if($this->request->is('post')){
            $usuario = $this->Auth->identify();
            if($usuario){
                $this->Auth->setUser($usuario);
                $this->set('usuario', $usuario);
                return $this->redirect('/');
            }
            $this->Flash->error(__('Usuário ou senha ínvalido, tente novamente'));
        }
		$this->set('title', 'Login');
	}

    public function logout(){
        $this->Auth->logout();
        $this->redirect('/');
    }

    protected function _setPassword($password){
        return (new DefaultPasswordHasher)->hash($password);
    }
}